# permissions for end users to view slacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slack-viewer-role
rules:
- apiGroups:
  - hook.overconfigured.dev
  resources:
  - slacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hook.overconfigured.dev
  resources:
  - slacks/status
  verbs:
  - get
