# permissions for end users to edit slacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slack-editor-role
rules:
- apiGroups:
  - hook.overconfigured.dev
  resources:
  - slacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hook.overconfigured.dev
  resources:
  - slacks/status
  verbs:
  - get
